Shop/Models/Car.cs
namespace Shop.Models
{
	public class Car
	{
		public int id { get; set; }

		public string name { get; set; }

		public string shortDesc { get; set; }

		public string longDesc { get; set; }

		public string img { get; set; }

		public int price { get; set; }

		public bool isFavourite { get; set; }

		public bool avalible { get; set; }
		public int categoryID { get; set; }

		public virtual Category Category { get; set; }
	}
}

Shop/Models/Category.cs
namespace Shop.Models
{
	public class Category
	{
		public int id { get; set; }
		public string categoryName { get; set; }
		public string desc { get; set; }
		public List<Car> cars { get; set; }
		

	}
}

Shop/Models/ErrorViewModel.cs
namespace Shop.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Shop/Models/Order.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Shop.Models
{
    public class Order
    {
        [BindNever]
        public int id { get; set; }

        [Display(Name = "Wpisz swoje imie")]
        [StringLength(10)]
        [Required(ErrorMessage = "Maksymalnie można wprowadzić 10 symboli")]
        public string name { get; set; }

        [Display(Name = "Wpisz swoje nazwisko ")]
        [StringLength(20)]
        [Required(ErrorMessage = "Maksymalnie można wprowadzić 20 symboli")]
        public string surname { get; set; }

        [Display(Name = "Wpisz swów adres")]
        [StringLength(40)]
        [Required(ErrorMessage = "Maksymalnie można wprowadzić 40 symboli")]
        public string adress { get; set; }

        [Display(Name = "Wpisz swój telefon")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(10)]
        [Required(ErrorMessage = "Maksymalnie można wprowadzić 10 symboli")]
        public string phone { get; set; }

        [Display(Name = "Wpisz swój email")]
        [DataType(DataType.EmailAddress)]
        [StringLength(30)]
        [Required(ErrorMessage = "Maksymalnie można wprowadzić 30 symboli")]
        public string email { get; set; }

        [BindNever]
        [ScaffoldColumn(false)]
        public DateTime orderTime { get; set; }
        public List<OrderDetail> orderDetails { get; set; }
    }
}

Shop/Models/OrderDetail.cs
namespace Shop.Models
{
    public class OrderDetail
    {
        public int id { get; set; }
        public int orderID { get; set; }
        public int CarID { get; set; }
        public uint price { get; set; }
        public virtual Car car { get; set; }
        public virtual Order order { get; set; }
    }
}

Shop/Models/ShopCart.cs
using Microsoft.EntityFrameworkCore;

namespace Shop.Models
{
	public class ShopCart
	{

		private readonly AppDBContent _appDBContent;
		public ShopCart(AppDBContent appDBContent)
		{
			_appDBContent = appDBContent;
		}

		public string ShopCartId { get; set; }
		public List<ShopCartItem> listShopItems { get; set; }

		public static ShopCart GetCart(IServiceProvider services)
		{
			ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;
			var context = services.GetService<AppDBContent>();
			string shopCartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();

			session.SetString("CartId", shopCartId);

			return new ShopCart(context)
			{
				ShopCartId = shopCartId
			};
		}
		public void AddToCart(Car car)
		{
			_appDBContent.ShopCartItem.Add(new ShopCartItem
			{
				ShopCartId = ShopCartId,
				car = car,
				price = car.price
			});

			_appDBContent.SaveChanges();
		}

		public List<ShopCartItem> getShopItems()
		{
			return _appDBContent.ShopCartItem.Where(c => c.ShopCartId == ShopCartId).Include(s => s.car).ToList();
		}
	}
}

Shop/Models/ShopCartItem.cs
namespace Shop.Models
{
	public class ShopCartItem
	{
		public int id { get; set; }
		public Car car { get; set; }
		public int price { get; set; }

		public string ShopCartId { get; set; }
	}
}

Shop/ViewModels/CarsListViewModel.cs
using Shop.Models;

namespace Shop.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> allCars { get; set; }
        public string currCategory { get; set; }
    }
}

Shop/ViewModels/HomeViewModel.cs
using Shop.Models;

namespace Shop.ViewModels
{
	public class HomeViewModel
	{
		public IEnumerable<Car> favCars { get; set; }
	}
}

Shop/ViewModels/ShopCartViewModel.cs
using Shop.Models;

namespace Shop.ViewModels
{
	public class ShopCartViewModel
	{
		public ShopCart shopCart { get; set; }
	}
}

Shop/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Interfaces;
using Shop.Models;
using Shop.ViewModels;

namespace Shop.Controllers
{
	public class CarsController : Controller
	{
		private readonly IAllCars _allCars;
		private readonly ICarsCategory _allCategories;

		public CarsController(IAllCars iAllCars, ICarsCategory iCarsCat)
		{
			_allCars = iAllCars;
			_allCategories = iCarsCat;
		}

		[Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public ViewResult List(string category)
		{
			string _category = category;
			IEnumerable<Car> cars = null;
			string currCategory = "";
			if(string.IsNullOrEmpty(category))
			{
				cars = _allCars.Cars.OrderBy(i => i.id);
			}
			else 
			{
				if(string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
				{
					cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Electrosamochody")).OrderBy(i => i.id);
					currCategory = "Electrosamochody";
                }
				else if(string.Equals("fuel", category, StringComparison.OrdinalIgnoreCase))
				{
                    cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Samochody klasyczne")).OrderBy(i => i.id);
					currCategory = "Samochody klasyczne";
                }
			}

            var carObj = new CarsListViewModel
            {
                allCars = cars,
                currCategory = currCategory
			};


			ViewBag.Title = "Strona z autami";
			
			return View(carObj);
		}
	}
}

Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Interfaces;
using Shop.ViewModels;

namespace Shop.Controllers
{
	public class HomeController : Controller
	{
		private IAllCars _carRep;
		
		public HomeController(IAllCars carRep)
		{
			_carRep = carRep;
		}

		public ViewResult Index()
		{
			var homeCars = new HomeViewModel
			{
                favCars = _carRep.getFavCars
			};
			return View(homeCars);
		}
	}
}

Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Interfaces;
using Shop.Models;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItems = shopCart.getShopItems();

            if(shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("", "Należy dodać towary do kosza");
            }
            else
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Zamówienie zostało zrealizowano";
            return View();
        }

    }
}

Shop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Interfaces;
using Shop.Models;
using Shop.ViewModels;

namespace Shop.Controllers
{
	public class ShopCartController : Controller
	{
		private IAllCars _carRep;
		private readonly ShopCart _shopCart; 

		public ShopCartController(IAllCars carRep, ShopCart shopCart)
		{
			_carRep = carRep;
			_shopCart = shopCart;
		}

		public ViewResult Index()
		{
			var items = _shopCart.getShopItems();
			_shopCart.listShopItems = items;

			var obj = new ShopCartViewModel
			{
				shopCart = _shopCart
			};
			return View(obj);
		}

		public RedirectToActionResult addToCart(int id)
		{
			var item = _carRep.Cars.FirstOrDefault(i => i.id == id);
			if (item != null) 
			{
				_shopCart.AddToCart(item);
			}
			return RedirectToAction("Index");
		}
	}
}

Shop/Views/Cars/List.cshtml
<h1>Wszystkie auta</h1>
<h3>@Model.currCategory</h3>
<div class="row mt-5 mb-2">
	@{
		foreach (Car car in Model.allCars)
		{
			@Html.Partial("AllCars", car)
		}
	}
</div>

Shop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Najlepsze auta</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.favCars)
        {
            @Html.Partial("AllCars", car)
        }
    }
</div>

Shop/Views/Order/Checkout.cshtml
@model Order

<div class="row">
	<h3>Składanie zamówienia</h3>
	<form asp-action="Checkout" method="post" class="form-horizontal">
		<div class="form-group">
			<label asp-for="name"></label>
			<div class="col-mb-5">
				<input asp-for="name" class="form-control" />
				<span asp-validation-for="name" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="surname"></label>
			<div class="col-mb-5">
				<input asp-for="surname" class="form-control" />
				<span asp-validation-for="surname" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="adress"></label>
			<div class="col-mb-5">
				<input asp-for="adress" class="form-control" />
				<span asp-validation-for="adress" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="phone"></label>
			<div class="col-mb-5">
				<input asp-for="phone" class="form-control" />
				<span asp-validation-for="phone" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="email"></label>
			<div class="col-mb-5">
				<input asp-for="email" class="form-control" />
				<span asp-validation-for="email" class="text-danger"></span>
			</div>
		</div>
		<br />
		<input class="btn btn-success" type="submit" value="Złożyć zamówienie" />
	</form>
</div>

Shop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Shop/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
	<img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
	<h2>@Model.name</h2>
	<p>@Model.shortDesc</p>
	<p>Cena: @Model.price.ToString("c")</p>
	<p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Dodać do kosza</a></p>
</div>

Shop/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">MVC_PPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List">Auta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/electro">Electro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/fuel">Benzynowe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Kosz</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2023 Paweł Paliak MVC · <a href="#">Regulamin</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Shop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container">
	@foreach (var el in Model.shopCart.listShopItems)
	{
		<div class="alert alert-warning mt-3">
			<b>Auto:</b> @el.car.name<br />
			<b>Cena:</b> @el.car.price.ToString("c")
		</div>
	}
	<hr />
	<a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Opłata</a>
</div>